# Generated by Django 5.2 on 2025-04-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_plant_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExampleModel",
        ),
    ]
