# Generated by Django 5.2 on 2025-05-06 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_examplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='last_watered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
